[package]
name = "restate-sdk-client"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
rust-version = { workspace = true }

[features]
default = []

[dependencies]
anyhow = { workspace = true }
reqwest = { version = "0.12.5" }

[dev-dependencies]
mockall = "0.13.0"
