[package]
name = "restate-sdk-core"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
rust-version = { workspace = true }

[features]
default = []

[dependencies]
anyhow = "1.0"
futures = "0.3"
futures-util = "0.3"
