[package]
name = "restate-sdk-examples"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
rust-version = { workspace = true }

[[example]]
doc = false
name = "example"
path = "src/example.rs"
required-features = []

[features]
default = []

[dependencies]
anyhow = "1.0"
bytes = "1.6.0"
futures-util = "0.3.30"
http-body-util = "0.1"
hyper = "1.3.1"
hyper-util = "0.1.3"
pin-project-lite = "0.2.14"
restate-sdk = { version = "0.1.0", path = "../crates/sdk" }
restate-sdk-types = { version = "0.1.0", path = "../crates/types" }
restate-service-protocol = { version = "0.1.0", path = "../crates/service-protocol" }
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
tokio-util = { version = "0.7.11", features = ["full"] }
prost = "0.12.6"
tokio-stream = "0.1.15"
tracing = "0.1"
tracing-futures = "0.2"
tracing-opentelemetry = "0.23.0"
tracing-subscriber = { version = "0.3", features = ["parking_lot", "env-filter", "registry"] }
uuid = { version = "1.8.0", features = ["v4"] }
