/*
 * Admin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HandlerMetadata {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "ty")]
    pub ty: models::HandlerMetadataType,
    #[serde(rename = "input_description")]
    pub input_description: String,
    #[serde(rename = "output_description")]
    pub output_description: String,
}

impl HandlerMetadata {
    pub fn new(name: String, ty: models::HandlerMetadataType, input_description: String, output_description: String) -> HandlerMetadata {
        HandlerMetadata {
            name,
            ty,
            input_description,
            output_description,
        }
    }
}

