/*
 * Admin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ProtocolType {
    #[serde(rename = "RequestResponse")]
    RequestResponse,
    #[serde(rename = "BidiStream")]
    BidiStream,

}

impl std::fmt::Display for ProtocolType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::RequestResponse => write!(f, "RequestResponse"),
            Self::BidiStream => write!(f, "BidiStream"),
        }
    }
}

impl Default for ProtocolType {
    fn default() -> ProtocolType {
        Self::RequestResponse
    }
}

