/*
 * Admin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RegisterDeploymentRequestAnyOf1 {
    /// ARN to use to discover/invoke the lambda deployment.
    #[serde(rename = "arn")]
    pub arn: String,
    /// Optional ARN of a role to assume when invoking the addressed Lambda, to support role chaining
    #[serde(rename = "assume_role_arn", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub assume_role_arn: Option<Option<String>>,
    /// Additional headers added to the discover/invoke requests to the deployment.
    #[serde(rename = "additional_headers", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub additional_headers: Option<Option<std::collections::HashMap<String, String>>>,
    /// If `true`, it will override, if existing, any deployment using the same `uri`. Beware that this can lead in-flight invocations to an unrecoverable error state.  By default, this is `true` but it might change in future to `false`.  See the [versioning documentation](https://docs.restate.dev/operate/versioning) for more information.
    #[serde(rename = "force", skip_serializing_if = "Option::is_none")]
    pub force: Option<bool>,
    /// If `true`, discovery will run but the deployment will not be registered. This is useful to see the impact of a new deployment before registering it.
    #[serde(rename = "dry_run", skip_serializing_if = "Option::is_none")]
    pub dry_run: Option<bool>,
}

impl RegisterDeploymentRequestAnyOf1 {
    pub fn new(arn: String) -> RegisterDeploymentRequestAnyOf1 {
        RegisterDeploymentRequestAnyOf1 {
            arn,
            assume_role_arn: None,
            additional_headers: None,
            force: None,
            dry_run: None,
        }
    }
}

