/*
 * Admin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SubscriptionResponse {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "source")]
    pub source: String,
    #[serde(rename = "sink")]
    pub sink: String,
    #[serde(rename = "options")]
    pub options: std::collections::HashMap<String, String>,
}

impl SubscriptionResponse {
    pub fn new(id: String, source: String, sink: String, options: std::collections::HashMap<String, String>) -> SubscriptionResponse {
        SubscriptionResponse {
            id,
            source,
            sink,
            options,
        }
    }
}

