/*
 * Admin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VersionInformation {
    /// Version of the admin server
    #[serde(rename = "version")]
    pub version: String,
    /// Minimum supported admin API version by the admin server
    #[serde(rename = "min_admin_api_version")]
    pub min_admin_api_version: i32,
    /// Maximum supported admin API version by the admin server
    #[serde(rename = "max_admin_api_version")]
    pub max_admin_api_version: i32,
}

impl VersionInformation {
    pub fn new(version: String, min_admin_api_version: i32, max_admin_api_version: i32) -> VersionInformation {
        VersionInformation {
            version,
            min_admin_api_version,
            max_admin_api_version,
        }
    }
}

